CREATE TABLE IF NOT EXISTS link_sys (
	  USER_ID	VARCHAR(50) NOT NULL
	, LINK_GROUP_NAME 	VARCHAR(20) NOT NULL
	, LID		int NOT NULL AUTO_INCREMENT
	, LINK_URI	VARCHAR(350)
	, LINK_TEXT 	VARCHAR(350)
	, GROUP_NAME 	VARCHAR(50)
) 
