CREATE TABLE IF NOT EXISTS link_sys (
	  USER_ID	VARCHAR(30) NOT NULL
	, SESSION 	VARCHAR(20) NOT NULL
	, LID		int NOT NULL AUTO_INCREMENT
	, LINK 		VARCHAR(350)
	, COMMENT 	VARCHAR(60)
	, GROUP_NAME 	VARCHAR(35)
) 
